//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int IdLog { get; set; }
        public string Operacion { get; set; }
        public string Modulo { get; set; }
        public int IdentificadorRegistro { get; set; }
        public string NombreTablaRegistro { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
    }
}
