//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public decimal Precio { get; set; }
        public int CantStock { get; set; }
        public string Estado { get; set; }
        public int PorcentajeDescuento { get; set; }
        public int UsuarioRegistro { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioActualizacion { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
    }
}
